# Generated by Django 4.2.5 on 2023-09-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbalances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hbalances',
            name='status',
            field=models.CharField(default='PROCESSED', max_length=30),
        ),
        migrations.AlterField(
            model_name='hbalances',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
